## Block matrix structure

$A = \begin{bmatrix}A_1 & A_2\\A_3 & A_4\end{bmatrix}$ where each $A_i$ is a smaller matrix.

### The Kronker Product
The two dimensional case:
$$
\begin{bmatrix} x_1 \\ x_2 \end{bmatrix} \otimes \begin{bmatrix} y_1 \\ y_2 \end{bmatrix} = \begin{bmatrix} x_1y_1 \\ x_1y_2 \\ x_2y_1 \\ x_2y_2 \end{bmatrix}
$$

![](http://om1hdizoc.bkt.clouddn.com/18-6-28/14597396.jpg)

In [17]:
vec_f = lambda x: x.reshape([-1], order="F") # vec_f stacks columns of x matrix vertically

The above function, `vec_f` performs unfolding the tensor into one dimensional vector. 
- Fiber, a fiber of tensor is fix all other dimensions except one.
- Slice, a slice of tensor is fix all other dimensions except two.

In [36]:
matrix_a = np.arange(12).reshape([2,3,2])
print(matrix_a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [37]:
print(vec_f(matrix_a)) 
# vec example, each smaller bracket represent a fiber, 
# smaller pair means something like [3,9], the length of this pair is the k-th dimension-size

[ 0  6  2  8  4 10  1  7  3  9  5 11]


In [38]:
print(matrix_a[:,1,:]) # a slice example

[[2 3]
 [8 9]]


## Tensor Unfold
- The goal is to unfold multidimentional tensor into matrix(2d). There are many ways to unfold a tensor. One way of doing so is the mode-k unfoldings.

- In a **model-k unfolding**, the mode-k fibers are assembled to produce an $n_k \times (N/n_k)$ matrix. Where $N = n_1***n_d$.

- In the lecture it's defined as horitontally stacking the column vectors of the n_k fibers. The column vectors represents changes of the unfixed dimension.

- Note, a 4th order tensor is a block matrix.

![](http://om1hdizoc.bkt.clouddn.com/18-6-27/73014202.jpg)

The above example turns 3-dimensional tensor into 2x2 matrix where's the dimension is 3 * 8. Obviously there are more than 1 way to reshape the 3-dimensinal tensor. 

## Contractions
### Permutations
There are many things I don't understand about permutations. Especially when it says transpose is of certain permutation.
$$vec(Y) = S_{p,r} \cdot vec(X)$$
Like what is this perfect permutation thingy??

### Contractions
Definition: A contraction between two tensors produces a third tensor through
a summation process.

Tensor Contractions: 

- Single index : Order(C) = Order(A) + Order(B) - 2
- Double index : Order(C) = Order(A) + Order(B) - 4

## Higher order SVDs

- Higher Order Singular Value Decomposition (HOSVD) 
    - matrix product = tensor times matrix product
- Kronecker Product Singular Value Decomposition (KPSVD)
    - Nearest Kronecker product problem
- Mode-k matrix product

In general, if $A \in \mathbb{R}^{n_1 \times \cdot \cdot \cdot \times n_d}$ and $M \in \mathbb{R}^{m_k \times n_k}$ then

$$
B(\alpha_1,...,\alpha_{k-1},i,\alpha_{k+1},....,\alpha_d) = \sum_{j=1}^{n_k}M(i,j) \cdot A(\alpha_1,...,\alpha_{k-1},j,\alpha_{k+1},....,\alpha_d)
$$

Notice in $B$ and $A$, the i and j are at the same axis. Even though the dimension size might differ. B has the same order but different dimension than A.

In a nutshell, the mode=k product of M and A is denoted by 
$$B = A \times_k M$$
Thus if $B = A \times_k M$. then $B$ is defined by $B_{(k)} = M \cdot A_{(k)}$

![](http://om1hdizoc.bkt.clouddn.com/18-7-2/1846517.jpg)

![](http://om1hdizoc.bkt.clouddn.com/18-7-2/63893655.jpg)

In a way, tucker product is a sucessive modal-k matrix product

- Inverse Factors $U_k$
- Core tensor $S$

We can compute core tensor $S$ with HOSVD. We can recover $A$ with tucker products. 

![](http://om1hdizoc.bkt.clouddn.com/18-7-2/14602997.jpg)